apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flowsource-plugin
  description: An example of a Backstage application.
  # Example for optional annotations
   annotations:
    github.com/project-slug: backstage/backstage
     backstage.io/techdocs-ref: dir:.
     github.com/project-slug: pep8speaks-org/pep8speaks
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
